import org.apache.hadoop.ipc.proto.GenericRefreshProtocolProtos.GenericRefreshResponseCollectionProtoOrBuilder;
public class FunctionUse7929 {
public void funcUse() {
GenericRefreshResponseCollectionProtoOrBuilder genericrefreshresponsecollectionprotoorbuilder = new GenericRefreshResponseCollectionProtoOrBuilder();
genericrefreshresponsecollectionprotoorbuilder.getResponsesCount();
}
}